site_name: Secret Santa Application
site_description: A modern Flask application for organizing Secret Santa events
repo_url: https://github.com/Kugeleis/wichteln
repo_name: Kugeleis/wichteln

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.instant
  palette:
    - scheme: default
      primary: red
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - User Guide:
    - Quick Start: guide/quickstart.md
    - Configuration: guide/configuration.md
    - Deployment: guide/deployment.md
  - API Reference:
    - Services: reference/services.md
    - Routes: reference/routes.md
    - Utils: reference/utils.md
  - Development:
    - Setup: DEVELOPMENT_SETUP.md
    - Testing: SINGLE_RESPONSIBILITY_TEST_ORGANIZATION.md
    - Documentation Strategy: SINGLE_POINT_OF_TRUTH_STRATEGY.md
    - GitHub Pages Deployment: GITHUB_PAGES_DEPLOYMENT.md
    - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md

watch:
  - services/
  - routes/
  - src/
